# Project information
site_name: BOSAGORA BizNet Documentation
site_url: https://bosagora.github.io/docs-biznet/en/
site_author: BOSAGORA
docs_dir: "../../source/en"
site_dir: "../../docs/en"

# Repository
repo_name: bosagora/docs-biznet
repo_url: https://github.com/bosagora/docs-biznet
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 BOSAGORA

# Configuration
theme:
  name: material
  custom_dir: "../../overrides/"
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  language: en

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

# Customization
extra:
  alternate:
    - name: English
      link: /docs-biznet/en/
      lang: en
    - name: 한국어
      link: /docs-biznet/kr/
      lang: kr
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bosagora1
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/BOSAGORA
    - icon: fontawesome/brands/medium
      link: https://medium.com/bosagora
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCjcTwkskyTmAwHpqv9Oynig
    - icon: fontawesome/brands/github
      link: https://github.com/bosagora

plugins:
  - search:
      lang: en

markdown_extensions:
  - attr_list

# Page tree
nav:
    - Home: index.md
    - BizNet:
        - Introduction: biznet/introduction.md
        - Consensus Engine: biznet/consensus.md
        - Develop:
            - BizNet MainNet: biznet/develop/mainnet.md
            - BizNet TestNet: biznet/develop/testnet.md
            - BizNet Explorers: biznet/develop/explorers.md
            - BizNet RPC: biznet/develop/rpc.md
            - Running Node:
                - Node: biznet/develop/running_node/node.md
                - Upgrading Geth : biznet/develop/running_node/upgrading.md
            - Deploy Smart Contract:
                - Using Remix IDE: biznet/develop/deploy_smart_contract/remix.md
                - Using Truffle: biznet/develop/deploy_smart_contract/truffle.md
                - Using Hardhat: biznet/develop/deploy_smart_contract/hardhat.md
            - ERC20 Tokens:
                - Introduction: biznet/develop/token/intoroduction.md
                - Issue Token: biznet/develop/token/issue.md
            - Deploy NFTs:
                - NFT Metadata Standard: biznet/develop/nft/metadata.md
                - Delply NFT on BizNet: biznet/develop/nft/deploy.md
        - Wallet:
            - Guide: biznet/wallet/guide.md
            - Key Management: biznet/wallet/key-management.md
            - Metamask: biznet/wallet/tutorials/metamask.md
    - BOASwap:
        - Introduction: boa_swap/introduction.md
        - Connecting to a Wallet: boa_swap/wallet/connectwallet.md
        - My assets:
            - My assets: boa_swap/myassets/myassets.md
        - Swap:
            - Introduction: boa_swap/swap/swap.md
            - How to use Swap: boa_swap/swap/use-swap.md
        - Pool:
            - Pool: boa_swap/pool/pool.md
        - Bridge:
            - Introduction: boa_swap/bridge/bridge.md
            - How to use Bridge: boa_swap/bridge/use-bridge.md
